### ISSUE TITLE
Fix Actions.parallel not working correctly

### ISSUE THREAD

**Issue by dandeduck** [Flash3388/FlashLib#60]
It's hard to remember, but this action did not work well in 2020. From what I can  recall, it worked fine the first time, but in subsequent uses (without code refresh or something) it didn't. In [this](https://github.com/Flash3388/Flash2020/commit/c69fc9f) commit the bug was discovered, look around I guess...

**Comment by tomtzook** [comment]
Your `ActionFactory.parallel` runs the actions without actually grouping them, simply by using `Action.start`, whereas `ParallelActionGroup` runs them grouped inside making the `Scheduler` unaware of their existence directly. 

However, there is also a difference in requirements handling (or at least, there was).
In version 2.X, the action groups did not copy requirements from added actions. This had to be set manually. This is something you don't do in `ActionFactory.initiationLineShootAction`, but you do do that in `ActionFactoryfullHighShootAction`.

This might as well be the problem.

**Comment by dandeduck** [comment]
I remember now, the issue was with the requirements... I guess if it does copy them now, feel free to close the issue

**Comment by tomtzook** [comment]
I would like to make sure first. It might have to wait until we have access to the robot so I can try to recreate the issue exactly.

**Comment by dandeduck** [comment]
We could go this Tuesday if you are up to it... Our school is opening then, but they have some schedule for the students. I don't think we would cause problems in terms of social distancing since it's just a couple of people in a separate room. But it's still probably a good idea to notify someone there beforehand.

**Comment by tomtzook** [comment]
We need approve this with Osher and the school administration first. Switch to DM!
